steps:
#Pull latest to build faster

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/cloudfame:$TAG_NAME'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and TAG_NAME variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/cloudfame:$TAG_NAME'
#deployment
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set',
   'image',
   'deployment',
   'cloudfame',
   'cloudfame=gcr.io/$PROJECT_ID/cloudfame:$TAG_NAME'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cloudfame-1'
